travis:
  secure:
    BINSTAR_TOKEN: j/ZphgZL/1vuYdF1zE8tv7AMkjW+eyFRbmzuqBILJZlaorfaLQhPa9SmRLZiDG0j3odXDwWVvdqubYI+EZsgbdL/ytvELfRokR2ECK/b+jPSdkrpe5KORBNpNdNOMx+2v6oKolo4n0XnhIrO/Q+fD+gx/7r/QoTK8wDdOw26Pais4IYyTpR8gHpysTnidaLk+PjLCKkobe7yulHiCkcqCqfVlreciPIpFeOGFpTjAyA+azSowK/eSGTuJYZKtwW7TVIbHOwqFsz/rGO8xXGqfQglO32fYjih5Qn2kjXcgBTV8iW75U6blV8EJnKGMBgSwHcLUDUqJZ/nejsD9ETQt+kt2apVyMLUdzOtugGEYfZoLoTPSdT31uDo8I3xci7G2Im6lptAsyUBzxGsFQOHhB+Uxu8MY4O5cBX6R1yr4rW01b3LyDAuBRlaLwTCiR5Wht+ITOjuU9S1ALmFe7D282tB7iNTy3NaolraSjQB3YVlRBnk9oiMv9Ge9g+9vvHwlENqXLz5hrmBRaPCljYmZg7t7v5BF60zb7tzhoo7yxcYb8mriM7qOWZSZbBrGZUj1QlLvXWslVvYcr9TR/ptiTxmNGL4F66bc4SHeWJXdk9b/UohFTTsiL6cRPf+FJ73KCoGQYAC8RwHzii0m9o71SFrVPvn4gYWvXAIWe/pQh4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
